server.port=8083
spring.application.name=notificacion-service

# Database per Service — BD exclusiva de notificacion-service
spring.datasource.url=jdbc:h2:mem:notificacion_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-notificacion

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificacion-group
spring.kafka.consumer.auto-offset-reset=earliest

# Topic Kafka (Coreografia)
kafka.topic.envio-creado=envio-creado
